### ISSUE TITLE
Self-signed cert error with testing/test-deployment.yaml

### ISSUE THREAD

**Issue by caiobegotti** [phenixblue/imageswap-webhook#2]
Hi, I have successfully set up imageswap-webhook on GKE but when trying the very same setup on-prem (offline env) I keep getting this error when running the test deployment from your repository:

```
ubuntu@juju:~/nymcard/devops/registry/imageswap-webhook$ kubectl apply -f ./testing/test-deploy.yaml -n test1
Error from server (InternalError): error when creating "./testing/test-deploy.yaml":
Internal error occurred: failed calling admission webhook "imageswap-webhook.k8s.twr.io":
Post https://imageswap-webhook-svc.kube-system.svc:443/?timeout=30s: x509: certificate signed by unknown authority
```

What is missing here? I have tried to manually copy the cert generated by your script to the cluster nodes (and updated the CA certs there) but no luck...

How can I debug it further? Any idea?

**Comment by phenixblue** [comment]
How is your on-prem cluster built? I have seen some issues when a Kubernetes distribution doesn't implement some underlying components correctly to take advantage of the in-cluster CA.

**Comment by phenixblue** [comment]
One example of this, was Kubernetes clusters deployed by early version of Pivotal's PKS. You can see a workaround documented in this fork: https://github.com/rhardt-pivotal/imageswap-webhook

Pivotal has since updates their tooling to maintain direct compatibility so the workaround is no longer needed in the latest versions (I think 1.3+)

**Comment by phenixblue** [comment]
Going to close this issue as stale. Feel free to comment if you have any updates.
