### ISSUE TITLE
Map doesn't parse correctly when a port is specified

### ISSUE THREAD

**Issue by sblair-metrostar** [phenixblue/imageswap-webhook#49]
**What happened**: 
My use case requires the mapping of a public endpoint to an internal Harbor proxy cache exposed via NodePort. Using the map below, the imageswap deployment reports the following error.
```
[2021-08-20 16:40:01,187] ERROR in app: Exception on / [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/app/imageswap.py", line 110, in mutate
    needs_patch = swap_image(container_spec)
  File "/app/imageswap.py", line 260, in swap_image
    swap_maps = build_swap_map(imageswap_maps_file)
  File "/app/imageswap.py", line 212, in build_swap_map
    (key, val) = line.split(":")
```

**What you expected to happen**:
The map should parse correctly and apply the mapped image to a pod on creation.

**How to reproduce it (as minimally and precisely as possible)**:
```
default:
registry.foobar.com:localhost:30003/foobar
```

**Anything else we need to know?**:
I've worked around this in the meantime by making the following change locally:

https://github.com/phenixblue/imageswap-webhook/blob/4be30ee56a321831b308a7906357e693edce04f5/app/imageswap/imageswap.py#L212

```python
(key, val) = line.split(":", 1)
```

**Environment**:

- Kubernetes version (use `kubectl version`): 1.20
- Cloud provider or hardware configuration: AWS/EKS
- Others:

**Comment by phenixblue** [comment]
Thanks @sblair-metrostar for bringing this to our attention.

After some examination, it looks like there are a couple of things we need to address around the inclusion of a port in the key or value portions of a map definition.

I have a fix in flight that should maintain backwards compatibility, but also move the map file syntax to better handle things like this.

Once the new release is out, to use a map with a port in either the key or value portions, you'll need to use `::` as the separator instead of `:`.

Example:

```
default::default.example.com
registry.waldo.com:8443::registry.garply.com # Swap map key that includes a port
registry.foo.com::localhost:30003/foo # Swap map value that includes a port
registry.bar.com:8443::registry.baz.com:30003/bar # Swap map key & value that include a port
```

Going forward, we will transition the map separator to `::` for all map definitions, regardless of the inclusion of a port.

**Comment by phenixblue** [comment]
Ok, looks like I've got things together for fixing this and some tests to cover this use case going forward. I just need to get the docs updated and then I should be good to merge the PR.
