### ISSUE TITLE
Ability to remove org/project during swap - MAPS

### ISSUE THREAD

**Issue by M4C4R** [phenixblue/imageswap-webhook#84]
**What would you like to be added**:

The ability to do what the deprecated legacy mode can do but within the MAPS method.
Currently, I cannot see a way to reproduce what the legacy method can do, which is to transform say `docker.io/a/b/c/d:v1` to `quay.io/x/y/z/d:v1`

Maybe we could use a new reserved keyword (**[replace]** in the example below) and wildcard, e.g.:

```
default::
[replace]quay.io*::docker.io/x/y/z
```

Expectation: `quay.io/a/b/c/d:v1 -> docker.io/x/y/z/d:v1`

The following would be equivalent, but now would not replace `quay.io/a/d:v1`.

```
default::
[replace]quay.io/a/b/*::docker.io/x/y/z
```

**Why is this needed**:

Sometimes the whole repo path needs amending, this ability appears to only be possible using legacy mode or exact matching - which is not ideal for when dealing with a large number of images.

**Comment by phenixblue** [comment]
Ok, I think I understand this. Is this a blocker for you currently? Is this an enhancement you are wanting to contribute?

The next big enhancement for ImageSwap will be a rewrite in Golang, and moving to using an actual configuration file. This should give a lot more flexibility in how swaps are defined and we can use first-party config rather than overloaded/hacky syntax. With those intentions, I've been trying to hold off on any additional map syntax changes.

No timeline on when the rewrite would be ready. If you're wanting to do the contribution, I am inclined to allow it in before the rewrite, otherwise I would probably want to record this as a constraint in the config design going forward.
